### ISSUE TITLE
I do not understand, why stats have one layer less?

### ISSUE THREAD

**Issue by goodboyanush-deeplite** [ZJULearning/COP#1]
```
## compute the feature
    for i, name in enumerate(only_weights_dict.keys()):
        if i == 0:
            last_name = name
        else:
            weight = only_weights_dict[name]
            stat = stat_func(weight)
            all_stat_dicts[last_name] = stat
            last_name = name
```

why are we skipping the first layer? And add the second layer's weight based correlation into the first name?

**Comment by cheerss** [comment]
For the 1st question: It is because the weights of each layer are used to predict the importance of the input feature maps; and the input feature maps of the first layer is the image itself which has 3 channels (RGB). It is inappropriate to remove anyone of these 3 three channels, so the first conv layer should be skiped.

For the 2nd question: Generally speaking, when we say "we prune n filters of a certain layer", we used to refer to the output channels of the layer. E.g., there are 32 channels in "conv0", and we prune 16 of them -- it means "conv0" output 32 channels (rather than its input contains 32 channels). However, as we said above, out algorithem focus on the input dimension. To keep them aligned, all names are post-positioned. E.g., supposing "conv0" and "conv1" are two consecutive layers, and "conv0" output 64 channels; then, we predict the importance of these 64 channels through the weights from "conv1", because they are the input of "conv1"; and then, we label them as "conv0" because they represent the importance of the output channels of "conv0".
